# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8cebfcf970904128c1f8c0c009492ec31a6d93ad65f0a0e2c7c0f20111dccfd1cfee6b3d17e3ed2dfd8356e5dd2da9512c553e46ea599c85c824e79ca076579

test:
  secret_key_base: bceecc029d84ee4d815a9514af808b7ef8e450e9855f74bb358e4850654773baa808fc7ecaeb91d5c7ce0f72b2662783e13c5badf26ae62c67d9c879dbfa40fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
